# Generated by Django 3.2.6 on 2021-08-28 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_channel_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_playing', models.BooleanField()),
                ('is_online', models.BooleanField()),
                ('channel_name', models.CharField(max_length=255)),
                ('game_room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='game.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bf1', models.CharField(max_length=100)),
                ('bf2', models.CharField(max_length=100)),
                ('bf1_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bf1_owner_game_state', to='game.player')),
                ('bf2_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bf2_owner_game_state', to='game.player')),
                ('state', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game', to='game.game')),
                ('whos_turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_state', to='game.player')),
            ],
        ),
    ]
