# Generated by Django 3.2.6 on 2021-08-31 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_player_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestate',
            name='name',
            field=models.CharField(default='GAME_NOT_STARTED', max_length=100),
        ),
    ]
